Algorithms/RadixSort/c++/RadixSort.cpp
=> Added RadixSort in C++

Programs/Rust/fibonacci_sequence.rs
Hi, i thought i would contribute to this repo with some of my own work. 
I have made a small rust program that asks the user how many sequences of the Fibonacci sequence they want to display and then the program will display it.
Thanks
=> Fibonacci Sequence Printer

Algorithms/quicksort/C++/QuickSort.cpp
I have added Quick Sort program in C++.
=> Added Quick Sort in C++

Algorithms/bubblesort/c++/bubblesort.cpp
Here is my contribution. Hope you will merge it.
=> added the code of bubble sort in c++

Programs/c/transform of a matrix.c
=> added program

Algorithms/binary_search/C++/binary_search.cpp
=> Added binary search in C++

Data_structures/LinkedList/Linked List.cpp, Data_structures/Queue/Queue.cpp, Data_structures/stack/Stack.cpp, README.md
I have implemented
- Stack
- Queue
- Linked List_
using STL in C++
@jeremie1112
=> Added all Data Structures using C++

Data_structures/Bubble sort/cpp/Bubble Sort.cpp, Data_structures/Insertion sort/cpp/Insertion Sort.cpp, Data_structures/Merge sort/cpp/Merge sort.cpp, Data_structures/Quick sort/cpp/Quick Sort.cpp, Data_structures/Selection sort/cpp/Selction Sort.cpp
Added bubble sort, selection sort, insertion sort, quick sort and merge sort cpp programs in defined manner by @jeremie1112
=> Added cpp sorting programs.

Algorithms/DFS_traversal_for_tree/c++/DFS_traversals_in_tree.cpp
I have added a new algorithm for DFS travsersal of trees. Thanks.
=> added DFS_traversal_program

Programs/C++/k-smallest-element.cpp
=> kth smallest element

Algorithms/Selection Sort in C lang, Algorithms/Selection_sort/C/Selection Sort in C lang.c
#19  Added a file for selection sort in C language  @jeremie1112
=> Selection Sort in C language

Programs/C++/balanced-parenthesis.cpp
checks if a strings parenthesis are valid or not. =)
=> added balanced parenthesis 

Programs/c/MaxMinOfArrayElements.c
I've added a C program to find min and max elements of an array in c folder of Programs folder.
=> Adding a new C program to find min and max elements of an array

Programs/C++/palindrome.cpp
Hello ! My name is Rajvir Singh . My email is 2018kucp1138@iiitkota.ac.in . 
I found  this repository really helpful with the programs simplified.
=> added a string program in c++

Data_structures/queue/Java/Queue.java, README.md
@jeremie1112 Please add .vscode/settings.json to gitignore
=> Added Queue's Java Implementation

Algorithms/Insertion_Sort/Java/InsertionSorting.java, README.md
=> Insertion sort java

Data_structures/Queue/C/queue.c, Data_structures/Queue/C/queue.h, Data_structures/Queue/C/test_program.c
Included test program of implementation, using an array-based queue.
=> add queue implenetation in c #1

Data_structures/LinkedList/python/linked_list.py
hey,
I've added python linked list code
=> Python_Linkedlist

Algorithms/quicksort/Clojure/project.clj, Algorithms/quicksort/Clojure/src/my_prog/main.clj, README.md
Add quick sort in Clojure including description
=> Add quick sort in Clojure

Algorithms/merge_sort/Clojure/project.clj, Algorithms/merge_sort/Clojure/src/my_prog/main.clj, README.md
Add the nice merge-sort algorithm in Clojure.
=> Add merge sort in Clojure

Programs/C++/binary_to_decimal.cpp
I have added the binary to decimal conversion program in C++.
=> Added Binary to Decimal Program

Algorithms/Insertion_Sort/C++/Esha-Insertion_Sort.cpp
=> Created Esha-Insertion_Sort.cpp

Algorithms/Selection sort/java/SelectionSort.java
=> selection sort in java

Programs/Python/Arithmetic_calculator.py
=> Arithmetic_calculator.py

Data_structures/stack/python/stack.py
hey,
I've added python stack code.
=> python stack added

Algorithms/merge_sort/java/merge_sort.java, README.md
Implemented Merge Sort in Java
=> Implemented Merge Sort in Java

Data_structures/LinkedList/C/circular_linked_list.c.c, Data_structures/LinkedList/C/doublly_linked_list.c, Data_structures/Queue/C/circular_Queue.c.c, Data_structures/stack/C/stack_Array.c.c
Added circular linked list , stack implementation using array ,doubly linked list and circular Queue.
=> Added Some More Feature

Programs/Python/longest_substring_without_repetition.py
Longest Substring Without Repeating Characters. No bugs.
=> Add Python Program 

Algorithms/Kadane's Algorithm/Python/maximum_subarray.py, Algorithms/Kadane's Algorithm/maximum_subarray.py
Created a folder for kadane's algorithm. Added python code. No bugs.
=> Added Kadane's Algorithm

Programs/C++/ThreeLargestElements.cpp
This C++ program finds out the three largest numbers in an array
I would be really glad if you merge this...I need this for Hacktober fest
=> Three_largest_elements

Algorithms/Kadane's Algorithm/Java/maximum_subarray.java, README.md
Implemented Kadane's Algorithm in Java
=> Implemented Kadane's Algorithm in Java

Data_structures/Heap/Heap.java, Data_structures/Heap/Java/Heap.java, README.md
Implemented MinHeap Data Structure
=> Implemented MinHeap Data Structure

Programs/C++/NUMBER_OF_DIGITS.cpp
Added solution to count the number of digits in programs folder.
=> Added solution to count the number of digits

Algorithms/countingSort/Java/CountingSort.java
Please review my code for Counting Sort implemented in java
=> Counting Sort Implemented in Java

Data_structures/Tree/C++/Binary Tree.cpp
C++ code for a binary tree. Let me know if any changes required.
=> Added Binary Tree implementation in C++

Programs/C++/spiral_print.cpp
This program prints a given 2d-array in a spiral wise manner.
=> Added spiral_print.cpp in Programs folder

Data_structures/LinkedList/C++/LinkedList(cpp).cpp
Created a linked list with multiple functions such as display, reverse, find occurrences for a particular number
=> Created a linked list with multiple functions

Data_structures/Tree/C++/Binary Search Tree.cpp
Program to Implement Search & Insertion in BST, Kindly let me know if any concerns.
=> Added Binary Search Tree (Search & Insertion) in C++

Programs/c/Binary Tree
=> Binary Tree

Algorithms/Bogosort/Python/bogosort.py
to see if someone else will create it on another language :)
=> Bogo sort implemented just for fun

Algorithms/Bozosort/Python/bozosort.py
to see if someone else will create it on another language :)
=> Bozo sort implemented just for fun

Algorithms/Breadth_First_Search/Java/GraphBFS.java
Implemented BFS in Java with a small Graph class.
=> Added Java BFS implementation with Graph structure

Programs/C++/friend function
i am adding the friend function
=> Create friend function

Programs/Java/input.java
=> input.java

Algorithms/quicksort/C++/Quick_Sort.cpp
I have added a C++ program to  perform sorting using Quicksort technique!!!
It is added in the folder : All_Programs_and_algorithms- > Algorithms -> quicksort-> C++ -> Quick_sort.cpp
Hope you find my contribution as useful and needful!!!        :  )
=> Added Quicksort Sorting method in C++ Language

Algorithms/binary_search/C++/binary_search.cpp
- Fix compilation error - include vector header
- Code was wrong - condition to check in main should have been binarySearch() != **-1**
- Fix whitespace issues
=> binary_search.cpp: Fix compilation and logic errors

Algorithms/Kadane'sAlgorithm/C++/Kadane's Algorithm.cpp
=> KadanesAlgorithm.cpp: Simplify Code

Data_structures/Tree/C++/Binary Search Tree.cpp
pointers need to be deleted manually. Deleting left, right , recursively deletes all nodes of the tree.
=> Add destructor to Binary Search Tree Class

Algorithms/binary_search/C++/binary_search_using_recursion.cpp
I have added a Recursive method to perform the Binary Search.
It is located in the folder as  : All_Programs_and_algorithms -> Algorithms->binary_search-> C++->binary_search_using_recursion.cpp
Hope you find my contribution as needful and helpful!!!
=> Added a Binary Search method using Recursion

Programs/C++/Components in a graph.cpp
#1 
Added Components in a graph program in C++
=> Added Components in a graph program in C++

Algorithms/binary_search/C/binarySearchIterative.c
Added Iterative Version of Binary Search
=> Iterative Binary Search

Data_structures/LinkedList/C/Implementation of Polynomial Using Linked List
Program For Implementation of Polynomial Using Linked List
=> Create Implementation of Polynomial Using Linked List

Algorithms/DFS_traversal_for_tree/C/inorderTraversal.c, Algorithms/DFS_traversal_for_tree/C/postorderTraversal.c, Algorithms/DFS_traversal_for_tree/C/preorderTraversal.c, Algorithms/LinearSearch/C/linearSearch.c
Added linear search algorithm.Please check it.
Thanks !
=> Added Linear Search in C

Algorithms/HeapSort/Python/heap_sort.py
Also see: #1 
Hi! I would like to add this implementation of the HeapSort Algorithm written in Python3. Hopes everything is ok with this PR but if I've made any mistake please let me know and I will change it!!
Thanks in advance! Cheers!! :)
=> Add HeapSort algorithm implementation in Python3

Algorithms/HeapSort/Java/HeapSortAlgo.java
Here, I have added the Heap Sort algorithm in Java, as it was not present in the repository.
I haven't changed any of the existing codes, just added a new file with my own code in a new folder.
This pull request is all my own work, my own code - I have not plagiarized.
This is a simple, clean and perfectly working solution!
=> Added the 'Heap Sort' algorithm in Java

Programs/Python/fibonacci_upto_n.py
Python Program to display the Fibonacci sequence up to n-th term
=> Created fibonacci_upto_n.py

Algorithms/LinearSearch/C++/LinearSearch.cpp
=> LinearSearch.cpp Added

Data_structures/AVL Tree/AVLTree.java, Data_structures/Binary Search Tree/BST.java, Data_structures/Binary Search Tree/BinarySearchTree.java, Data_structures/Binary Tree/avl_tree.cpp, Data_structures/Binary Tree/intro.cpp, Data_structures/Binary Tree/rightview.cpp, Data_structures/Binary Tree/tree_traversal.cpp, Data_structures/Collection/AbstractCollection.java, Data_structures/Collection/ArrayCollection.java, Data_structures/Collection/Collection.java, Data_structures/Collection/Iterator.java, Data_structures/Collection/LinkedCollection.java, Data_structures/Collection/Main.java, Data_structures/Disjoint Set/base.cpp, Data_structures/Map/Hashtable.java, Data_structures/Map/HashtableStraightChaining.java, Data_structures/Map/Main.java, Data_structures/Map/Map.java, Programs/Java/Java Text Editor/MyFileQueue.java, Programs/Java/Java Text Editor/MyFileStack.java, Programs/Java/Java Text Editor/TextEditor.java, Programs/Java/Program for Tower of Hanoi.java
I have added a Program of Text Editor(works like Notepad) using Java.
=> Added Text Editor Program In java

Algorithms/LinearSearch/Python/linear_search.py, README.md
Add linear search algorithm in python. Also updated the ```README.md``` accordingly.
=> Add linear search in python

Programs/c/Sparse to Compact form conversion and vice-versa/convert.h, Programs/c/Sparse to Compact form conversion and vice-versa/main.c
I have added a program to convert a sparse matrix to its compact form and vice versa.
=> Convert sparse matrix to compact and vice-versa

Programs/c/Infix to Postfix expression Conversion and Evaluation/main.c, Programs/c/Infix to Postfix expression Conversion and Evaluation/stack.h
A program to convert infix expression to postfix and evaluate it
=> Added infix to postfix conversion and evaluation program

Programs/C++/Trapping_Rain_Water.cpp
https://github.com/jeremie1112/All_Programs_and_algorithms/issues/151
=> Trapping Rain Water CPP Program

Data_structures/Tree/Python/BinaryTree.py
Add python BinaryTree pls #beginner #good first issue #hacktoberfest #hacktoberfest2021 
#help wanted
=> Adding a test file to new_branch

Programs/C++/Birthday_Cake_candle.cpp
Birthday_cake_candle  c++ programme is added
=>  Birthday_Cake_candles programme is added

Algorithms/Kadane'sAlgorithm/C++/Kadane's Algorithm.cpp, Data_structures/Matrix/C++/SparseMatrix.cpp, Data_structures/Matrix/C/SparseMatrix.c, Data_structures/Matrix/C/polynomial.c, Programs/c/FindDuplicatesinString.c
- Added Sparse matrix ,polynomial addition program
- Added program to find duplicates in string 
- minor edit in one code
=> added programs in DSA

Algorithms/countingSort/C++/CountingSortAlternative.cpp
Hey there, I had raised an issue of adding an alternative algorithm for the counting sort here it is. Open to suggestions and Improvements.
=> Alternative Algorithm of Counting Sort added

Programs/C++/Trapping_Rain_Water.cpp, Programs/C++/Trapping_Rain_Water_Improved.cpp
Improved algorithm from O(n<sup>2</sup>) --> O(n). Please review and let me know.
Thanks
=> improved trapping_rain_water idea

Programs/C++/maximumCircularSubarraySum.cpp
Please review the programme writtern in C++. Let me know any changes.
Thanks
=> add max ciruclar-array-sum

Programs/Python/EvenDigit.py
This program finds all numbers with even digits within a given range.
=> Added EvenDigits.py

Algorithms/countingSort/C/CountingSort.c
Added counting sort algorithm in C.
=> Hacktoberfest2022 contribution

Programs/Java/BMICalc.java
This program is able to calculate your body mass index with the information you provide including your height and weight.
=> Creation of BMICalc.java

Algorithms/Rabin_Karp/C++/rabin_karp.cpp
Heyy @jeremie1112 
Please review and let me know any changes
Thanks
=> add rabin-karp algorithm

Algorithms/quicksort/java/QuickSortYash.java
**[Java program for implementation of Quick Sort added](https://github.com/YashSalunke12/All_Programs_and_algorithms/tree/yash/Algorithms/quicksort/java)**
=> Java program for implementation of QuickSort added

Programs/C++/printPermutationsWithDistinctCharecters.cpp
Please review and let me know. Thanks.
=> add printPermutations

Programs/C++/fibonacci_sum_last_digit.cpp
The last digit of sum of the first n Fibonacci numbers
Please review and accept for hacktoberfest
Let me know if there are any issues
=> Added new program

Data_structures/stack/C++/stack_implementation_with_max.cpp
Added stack implementation while maintaining max using cpp
Please review and accept for hacktoberfest
Let me know if there are any issues
=> Added data structure stack_implementation_with_max

Programs/Python/MorseCodeGame.py
#225 
#Changes_accepted 
plz  merge it and mark as "hactoberfest accepted"
=> MorseCodeGame.py

Programs/Python/BankManagementSystem.py
=> BankManagementSystem.py

Algorithms/binary_search/Python/binarysearch.py
=> added files for binary search

Programs/Python/CheckGitUserName.py
This script allows verify if an username is available or not.
=> CheckGitUserName.py

Programs/Python/NetSpeedTest.py
This script will check the speed of your current internet connection.
=> NetSpeedTest.py

Programs/Python/snakegamebyTurtuleModule.py
=> snakegamebyTurtuleModule.py

Programs/Python/abundant_number.py
I have added a program to check whether an input number is an abundant number or not, in python under the Programs/Python directory. (An abundant number is a number the sum of whose proper factors are greater than that of the number itself)
=> Added implementation for Abundant Number in Python 
